import formworkImg from '../src/assets/images/formwork.jpg'
import mixerImg from '../src/assets/images/mixer.webp'
import scaffoldingImg from '../src/assets/images/scaffolding.webp'
import toolsImg from '../src/assets/images/tools.jpg'
import wheelbarrow from '../src/assets/images/wheelbarrow.jpg'
import spotlight from '../src/assets/images/spotlight.jpg'
import bayok from '../src/assets/images/bayok.webp'
import barrel from '../src/assets/images/barrel.webp'
import {v4 as uuidv4} from 'uuid'

const products = [
   {id: 1, title: 'Opalobka', value: 'formwork', img: formworkImg, data: [
      {
         id: uuidv4(),
         title: '25x1',
         height: "25",
         length: '1',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },
      {
         id: uuidv4(),
         title: '25x1.5',
         height: '25',
         length: '1.5',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },
      {  
         id: uuidv4(),
         title: '25x2',
         height: '25',
         length: '2',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },
      {
         id: uuidv4(),
         title: '25x2.5',
         height: '25',
         length: '2.5',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },
      {
         id: uuidv4(),
         title: '25x3',
         height: '25',
         length: '3',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },
      {
         id: uuidv4(),
         title: '25x3.5',
         height: '25',
         length: '3.5',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },
      {
         id: uuidv4(),
         title: '25x4',
         height: '25',
         length: '4',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },
      {
         id: uuidv4(),
         title: '40x1',
         height: '40',
         length: '1',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '40x1.5',
         height: '40',
         length: '1.5',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '40x2',
         height: '40',
         length: '2',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '40x2.5',
         height: '40',
         length: '2.5',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '40x3',
         height: '40',
         length: "3",
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '40x3.5',
         height: '40',
         length: '3.5',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '40x4',
         height: '40',
         length: '4',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '50x1',
         height: '50',
         length: '1',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '50x1.5',
         height: '50',
         length: '1.5',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '50x2',
         height: '50',
         length: '2',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '50x2.5',
         height: '50',
         length: '2.5',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '50x3',
         height: '50',
         length: '3',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '50x3.5',
         height: '50',
         length: '3.5',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '50x4',
         height: '50',
         length: "4",
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '60x1',
         height: '60',
         length: "1",
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '60x1.5',
         height: '60',
         length: '1.5',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '60x2',
         height: '60',
         length: '2',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '60x2.5',
         height: '60',
         length: '2.5',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '60x3',
         height: '60',
         length: '3',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '60x3.5',
         height: '60',
         length: '3.5',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },   
      {
         id: uuidv4(),
         title: '60x4',
         height: '60',
         length: '4',
         select: ['metr', 'dona'],
         amount: 10,
         rent: 0,
         category: 'opalobka',
      },
   ]},
   {id: 2, title: 'Lesa', value: 'scaffolding', img: scaffoldingImg, data: [
      {id: uuidv4(), title: 'lesa', select: ['dona', 'komp'], amount: 20, rent: 0, category: 'lesa',},
   ]},
   {id: 3, title: 'Meshalka', value: 'mixer', img: mixerImg, data: [
      {id: uuidv4(), title: 'meshalka', select: ['dona'], amount: 2, rent: 0, category: 'meshalka',},
   ]},
   {id: 4, title: 'Boshqalar', value: 'others', img: toolsImg, data: [
      {id: uuidv4(), title: 'otboyniy', select: ['kun', 'soat'], amount: 2, rent: 0, category: 'boshqalar',},
      {id: uuidv4(), title: 'perforator', select: ['kun', 'soat'], amount: 2, rent: 0, category: 'boshqalar',},
      {id: uuidv4(), title: 'bolgarka', select: ['kun', 'soat'], amount: 2, rent: 0, category: 'boshqalar',},
      {id: uuidv4(), title: 'svarka apparat', select: ['kun', 'soat'], amount: 2, rent: 0, category: 'boshqalar',},
      {id: uuidv4(), title: 'drel', select: ['kun', 'soat'], amount: 3, rent: 0, category: 'boshqalar',},
      {id: uuidv4(), title: 'kompressor', select: ['kun', 'soat'], amount: 1, rent: 0, category: 'boshqalar',},
   ]},
   {id: 5, title: 'Arava', value: "wheelbarrow", img: wheelbarrow, data: [
      {id: uuidv4(), title: 'arava katta', select: ['dona'], amount: 1, rent: 0, category: 'arava',},
      {id: uuidv4(), title: 'arava kichik', select: ['dona'], amount: 1, rent: 0, category: 'arava',},
   ]},
   {id: 6, title: 'Projektor', value: 'spotlight', img: spotlight, data: [
      {id: uuidv4(), title: 'projektor', select: ['dona'], amount: 4, rent: 0, category: 'projektor',}
   ]},
   {id: 7, title: 'Bayok', value: "bayok", img: bayok, data: [
      {id: uuidv4(), title: 'bayok katta', select: ['dona'], amount: 1,  rent: 0, category: 'bayok',},
      {id: uuidv4(), title: 'bayok kichik', select: ['dona'], amount: 1,  rent: 0, category: 'bayok',},
      {id: uuidv4(), title: 'karita', select: ['dona'], amount: 1,  rent: 0, category: 'bayok',},
   ]},
   {id: 8, title: 'Bochka', value: 'barrel', img: barrel, data: [
      {id: uuidv4(), title: 'bochka', select: ['dona'], amount: 3, rent: 0, category: 'bochka',},
   ]}
]
export {products}